#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../upgrade-to-3.9/ConvertTrlXmlToPoCommand.php';

use Symfony\Component\Console\Application;

$application = new Application('trl', '0.1');
$application->add(new ConvertTrlXmlToPoCommand);
$application->run();
